// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(VaultonDbContext))]
    [Migration("20260127130705_AddRecoveryVerifiers")]
    partial class AddRecoveryVerifiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DomainTag")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DomainTag");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AdminVerifier")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CryptoSchemaVer")
                        .HasColumnType("integer");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<int>("KdfMode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RkVerifier")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("S_AdminVerifier")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("S_Pwd")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("S_Rk")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("S_Verifier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Entry", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Crypto.EncryptedValue", "Payload", b1 =>
                        {
                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("CipherText")
                                .IsRequired()
                                .HasMaxLength(4096)
                                .HasColumnType("bytea")
                                .HasColumnName("Payload_CipherText");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("bytea")
                                .HasColumnName("Payload_Nonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("bytea")
                                .HasColumnName("Payload_Tag");

                            b1.HasKey("EntryId");

                            b1.ToTable("Entries");

                            b1.WithOwner()
                                .HasForeignKey("EntryId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.OwnsOne("Core.Crypto.EncryptedValue", "MkWrapPwd", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("CipherText")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapPwd_CipherText");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapPwd_Nonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapPwd_Tag");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Core.Crypto.EncryptedValue", "MkWrapRk", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("CipherText")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapRk_CipherText");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapRk_Nonce");

                            b1.Property<byte[]>("Tag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("bytea")
                                .HasColumnName("MkWrapRk_Tag");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("MkWrapPwd")
                        .IsRequired();

                    b.Navigation("MkWrapRk")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
